import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {jaJP}  from "@clerk/localizations";
import { TRPCProvider } from "@/trpc/client";

const font = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/" localization={jaJP}>
      <html lang="ja">
        <body className={font.className}>
          <TRPCProvider>
          {children}
          </TRPCProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
